DROP TABLE REPLICATION_PROCESSING;
CREATE TABLE REPLICATION_PROCESSING(
ID                  NUMBER(12) PRIMARY KEY,
RUN_NO              NUMBER(12) NOT NULL,
PARENT_TABLE        VARCHAR2(70) NOT NULL,
CHILD_TABLE         VARCHAR2(70),
ENTRY_TYPE          VARCHAR2(70),
PROCESS_STATEMENT   CLOB,
PROCESS_MSG         VARCHAR2(4000),
STATEMENT_HASH      VARCHAR2(4000)
);

CREATE SEQUENCE REPLICATE_LOG_PK_SEQ;
CREATE SEQUENCE REPLICATE_TRK_SEQ;